ignore:
  - "tests/**"
  - "experiments/**"
  - "**/__pycache__"
  - "**/*.pyc"
  - "setup.py"
  - "scripts/generate_ssh_config.py"
  - "scripts/test_ssh_device_ci.py"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 5%
