name: OVMobileBench CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      device_serial:
        description: 'Mobile device serial'
        required: false

# Cancel in-progress runs when a new commit is pushed to the same PR or branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # , windows-latest]
    uses: ./.github/workflows/ci-orchestrator.yml
    with:
      os: ${{ matrix.os }}
      device_serial: ${{ github.event.inputs.device_serial || 'emulator-5554' }}
    secrets: inherit
