name: OVMobileBench CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      device_serial:
        description: 'Android device serial'
        required: false

jobs:
  ci-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    uses: ./.github/workflows/reusable-ci.yml
    with:
      os: ${{ matrix.os }}
      device_serial: ${{ github.event.inputs.device_serial || 'emulator-5554' }}

  # Optional: Run on a self-hosted runner with a real device
  device-test-adb:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[device-test-adb]')
    needs: ci-matrix
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Check ADB devices
        run: adb devices

      - name: Run minimal benchmark
        env:
          DEVICE_SERIAL: ${{ github.event.inputs.device_serial || 'emulator-5554' }}
        run: |
          ovmobilebench list-devices
          # Uncomment when ready:
          # ovmobilebench all -c experiments/android_example.yaml --dry-run

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-adb
          path: experiments/results/
          retention-days: 30