name: OVMobileBench CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      device_serial:
        description: 'Mobile device serial'
        required: false

jobs:
  ci-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # , windows-latest]
    uses: ./.github/workflows/reusable-ci-simple.yml
    with:
      os: ${{ matrix.os }}
      device_serial: ${{ github.event.inputs.device_serial || 'emulator-5554' }}
