name: OVMobileBench CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      device_serial:
        description: 'Android device serial'
        required: false

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run Black
        run: black --check ovmobilebench tests

      - name: Run Ruff
        run: ruff check ovmobilebench tests

      - name: Run MyPy
        run: mypy ovmobilebench --ignore-missing-imports

      - name: Run tests
        run: pytest tests/ -v --cov=ovmobilebench --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  build-package:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          pip install --upgrade pip
          pip install build setuptools wheel

      - name: Build package
        run: python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7

  dry-run:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Validate example config
        run: |
          python -c "from ovmobilebench.config.loader import load_experiment; load_experiment('experiments/android_example.yaml')"

      - name: CLI help test
        run: |
          ovmobilebench --help
          ovmobilebench build --help
          ovmobilebench run --help

  # Optional: Run on a self-hosted runner with a real device
  device-test-adb:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[device-test-adb]')
    needs: build-package
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Check ADB devices
        run: adb devices

      - name: Run minimal benchmark
        env:
          DEVICE_SERIAL: ${{ github.event.inputs.device_serial || 'emulator-5554' }}
        run: |
          ovmobilebench list-devices
          # Uncomment when ready:
          # ovmobilebench all -c experiments/android_example.yaml --dry-run

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: experiments/results/
          retention-days: 30
