name: CI Orchestrator

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      device_serial:
        required: false
        type: string
        default: 'emulator-5554'

jobs:
  # Stage 1: Pre-commit checks (always runs on ubuntu-latest)
  pre-commit:
    uses: ./.github/workflows/stage-pre-commit.yml
    secrets: inherit

  # Stage 2: Test
  test:
    needs: pre-commit
    uses: ./.github/workflows/stage-test.yml
    with:
      os: ${{ inputs.os }}
    secrets: inherit

  # Stage 3: Build Package (runs in parallel with validation)
  build:
    needs: test
    uses: ./.github/workflows/stage-build.yml
    with:
      os: ${{ inputs.os }}
    secrets: inherit

  # Stage 4: Validation (runs in parallel with build)
  validation:
    needs: test
    uses: ./.github/workflows/stage-validation.yml
    with:
      os: ${{ inputs.os }}
    secrets: inherit

  # Stage 5: Device Tests (runs after build and validation)
  device-tests:
    needs: [build, validation]
    uses: ./.github/workflows/stage-device-tests.yml
    with:
      os: ${{ inputs.os }}
      device_serial: ${{ inputs.device_serial }}
    secrets: inherit
