name: Device Tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      device_serial:
        required: false
        type: string
        default: 'emulator-5554'

jobs:
  device-test-ssh:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            setup.py

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Test SSH with Paramiko test server
        shell: bash
        run: |
          set -e
          python tests/test_ssh_device_ci.py

      - name: Run benchmark dry-run via SSH
        shell: bash
        env:
          PYTHONIOENCODING: utf-8
          PYTHONUTF8: 1
        run: |
          set -e
          ovmobilebench all -c experiments/ssh_test_ci.yaml --dry-run

      - name: Upload SSH test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-ssh-${{ inputs.os }}
          path: experiments/results/
          retention-days: 30

  device-test-adb:
    if: |
      (github.event_name == 'workflow_dispatch' || 
       contains(github.event.head_commit.message, '[device-test-adb]')) && 
       inputs.os == 'ubuntu-latest'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            setup.py

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Check ADB devices
        run: adb devices

      - name: Run minimal benchmark
        env:
          DEVICE_SERIAL: ${{ inputs.device_serial }}
        run: |
          ovmobilebench list-devices
          # Uncomment when ready:
          # ovmobilebench all -c experiments/android_example.yaml --dry-run

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-adb-${{ inputs.os }}
          path: experiments/results/
          retention-days: 30
